name: CI

on:
  push:
    branches:
      - test-ci

env:
  FORCE_COLOR: 3

jobs:
  checks:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        os: [ubuntu-latest] # macos-latest doesn't work due to clang -fopenmp issues
        include:
        - os: ubuntu-latest
          INSTALL_DEPS: sudo apt-get install -y libfftw3-dev
          CC: gcc
          CXX: g++
#        - os: macos-latest
#          INSTALL_DEPS: brew install fftw
#          CC: clang
#          CXX: clang++

    steps:
      # Install Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip' # Cache pip dependencies
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
#      # Upgrade pip
#      - name: Install pip
#        run: python -m pip install --upgrade pip
      # Install dependencies
      - name: Install dependencies
        run: ${{ matrix.INSTALL_DEPS }}
      # Checkout the project
      - uses: actions/checkout@v4
      # Build package
      - name: Build package
        run: pip install -e .[test]
      # Test package
      - name: Test package
        run: python -m unittest

  dist:
    name: Build and inspect distribution build
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:

        
#      # Upgrade pip
#      - name: Install pip
#        run: python -m pip install --upgrade pip build twine
#      # Build pipic
#      - name: Build pipic
#        run: python -m build
#      # Check the build files
#      - name: Check build files
#        run: twine check dist/*
      # Install dependencies
      - name: Install dependencies
        run: sudo apt-get install -y libfftw3-dev
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: hynek/build-and-inspect-python-package@v1
