name: CI

on:
  push:
    branches:
      - test-ci

jobs:
  checks:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        runs-on: [ubuntu-latest, macos-latest]

    steps:
      # Checkout the project
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Install Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip' # Cache pip dependencies
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      # Upgrade pip
      - name: Install pip
        run: python -m pip install --upgrade pip
#      # Upgrade pip
#      - name: Install pip
#        run: python -m pip install --upgrade pip build twine
#      # Install fftw3
#      - name: Install fftw3
#        run: sudo apt update && sudo apt-get install -y libfftw3-dev
      # Install FFTW
      - name: Setup FFTW (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get install -y libfftw3-dev

      - name: Setup FFTW (macOS)
        if: runner.os == 'macOS'
        run: brew install fftw
        
#      # Build pipic
#      - name: Build pipic
#        run: python -m build
#      # Check the build files
#      - name: Check build files
#        run: twine check dist/*
      # Build pipic
      - name: Build pipic
        run: pip install -e .

  dist:
    name: Build and inspect distribution build
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: hynek/build-and-inspect-python-package@v1
